apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-d4e9a0278e6c484195f4ad4a60efb418-depl
  labels:
    app: coll-d4e9a0278e6c484195f4ad4a60efb418
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-d4e9a0278e6c484195f4ad4a60efb418
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-d4e9a0278e6c484195f4ad4a60efb418
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-d4e9a0278e6c484195f4ad4a60efb418
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-d4e9a0278e6c484195f4ad4a60efb418
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping